/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzeria.GUI;

import alertas.principal.WarningAlertCerrar;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.StringJoiner;
import java.util.stream.Collectors;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import pizzeria.DAL.loginDAL;

/**
 *
 * @author Zero
 */
public class logGUI extends javax.swing.JFrame {

    
    loginDAL objloginDAL = new loginDAL();
    public static int PERMISOS = 0;
    /**
     * Creates new form logGUI
     */
    public logGUI() {
        initComponents();
        cargarfondo();
        cargarusuariofondo();
        cargarpassfondo();
        
        
       
    }
    
    public int LogIn()
    {
     //StringJoiner joiner = new StringJoiner("','", "'", "'");
     String usuario = '\''+ txtusuario.getText() + '\'';
     String pass = '\''+ txtpass.getText() + '\'';
     int aprobado = objloginDAL.LogIn(usuario, pass);
     PERMISOS = obtenerPermiso(usuario,pass);
     return aprobado;
    }
    
    public int obtenerPermiso(String usuario, String pass)
    {
     //StringJoiner joiner = new StringJoiner("','", "'", "'");
     //String usuario = '\''+ txtusuario.getText() + '\'';
     //String pass = '\''+ txtpass.getText() + '\'';
        
    int permiso = objloginDAL.obtenerPermiso(usuario, pass);
    
    int credencial = TipoEmpleado(permiso);
    
    return credencial;
    
    }
    
     public int TipoEmpleado(int permiso) {
    // Notice that the following is final, but not static, and is not given a value upfront.
    int admin = 1;
    int emp = 2;
    int tipoEmpleado  = 0;
    
    if(permiso == admin)
    {
    tipoEmpleado = admin;
    }
    else if (permiso == emp)
    {
    tipoEmpleado = emp;
    }
    
    
    
    return tipoEmpleado;
    
    }
     
    
    public void cargarfondo(){
    //String img = ("loginfondo.jpeg");
      // ImageIcon mg = new ImageIcon(img);
       ImageIcon myimage = new ImageIcon (Toolkit.getDefaultToolkit().getImage(getClass().getResource("loginfondo.png")));
        
        Image img1 = myimage.getImage();
        Image img2 = img1.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon Logo = new ImageIcon(img2);
       jLabel1.setIcon(Logo);
      
    }
    
    public void cargarusuariofondo(){
    //String img = ("loginfondo.jpeg");
      // ImageIcon mg = new ImageIcon(img);
       ImageIcon myimage = new ImageIcon (Toolkit.getDefaultToolkit().getImage(getClass().getResource("campo-usuario.png")));
        
        Image img1 = myimage.getImage();
        Image img2 = img1.getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon Logo = new ImageIcon(img2);
       jLabel2.setIcon(Logo);
       
    }
    
    
    
   
    
    
    public void cargarpassfondo(){
    //String img = ("loginfondo.jpeg");
      // ImageIcon mg = new ImageIcon(img);
       ImageIcon myimage = new ImageIcon (Toolkit.getDefaultToolkit().getImage(getClass().getResource("campo-contrasena.png")));
        
        Image img1 = myimage.getImage();
        Image img2 = img1.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon Logo = new ImageIcon(img2);
       jLabel3.setIcon(Logo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        materialButtonCircle1 = new principal.MaterialButtonCircle();
        btnlogin = new principal.MaterialButtonCircle();
        txtusuario = new app.bolivia.swing.JCTextField();
        txtpass = new jpass.JRPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        materialButtonCircle1.setText("materialButtonCircle1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 150));
        setMinimumSize(new java.awt.Dimension(200, 430));
        setPreferredSize(new java.awt.Dimension(500, 430));
        setResizable(false);
        getContentPane().setLayout(null);

        btnlogin.setBackground(new java.awt.Color(204, 0, 0));
        btnlogin.setText("Ingresar");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin);
        btnlogin.setBounds(220, 310, 230, 50);

        txtusuario.setPlaceholder("Ingrese su Usuario");
        getContentPane().add(txtusuario);
        txtusuario.setBounds(230, 162, 230, 30);

        txtpass.setPlaceholder("Ingrese su Contraseña");
        getContentPane().add(txtpass);
        txtpass.setBounds(230, 232, 230, 30);

        jLabel3.setText("CON");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 220, 290, 50);

        jLabel2.setText("US");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 150, 290, 50);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
       //System.out.println(LogIn());
       
       int aprobado = (LogIn());
       if (aprobado == 1)
       {
           
           
     //StringJoiner joiner = new StringJoiner("','", "'", "'");
     //String usuario = '\''+ txtusuario.getText() + '\'';
     //String pass = '\''+ txtpass.getText() + '\'';
     //int PERMISOS = objloginDAL.obtenerPermiso(usuario, pass);
       principalGUI mprincipal = new principalGUI();
        mprincipal.setVisible(rootPaneCheckingEnabled);
        this.setVisible(false);
       }
       else if (aprobado == 0)
       {
        WarningAlertCerrar wa = new WarningAlertCerrar(this, true);
        wa.titulo.setText("Usuario o Contraseña erroneos");
        wa.msj.setText("Verifique y vuelva a intentar");
        wa.msj1.setText("");
        wa.setVisible(true);    
           
       //JOptionPane.showMessageDialog(null,"El usuario o Contraseña ingresados no son correctos, verifique y vuelva a intentarlo", "Acceso Denegado",JOptionPane.INFORMATION_MESSAGE);
       }
    }//GEN-LAST:event_btnloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logGUI().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private principal.MaterialButtonCircle btnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private principal.MaterialButtonCircle materialButtonCircle1;
    private jpass.JRPasswordField txtpass;
    private app.bolivia.swing.JCTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
